name: Trigger auto deployment for thinkr-searxng

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/thinkr-searxng-AutoDeployTrigger-bbdc42d5-20f8-4ab3-83d1-e3ecc71ad4b1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.THINKRSEARXNG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.THINKRSEARXNG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.THINKRSEARXNG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.THINKRSEARXNG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.THINKRSEARXNG_REGISTRY_PASSWORD }}
          containerAppName: thinkr-searxng
          resourceGroup: Altair-axis
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


